[package]
name = "quantum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.4"
rand = "0.8.5"
float-cmp = "0.9.0"
num-traits = "0.2.18"